#!/usr/bin/env python
# Copyright 2014 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import subprocess
import sys

OVS_VERSIONS = [
 "1.4.6",
 "1.5.0",
 "1.6.1",
 "1.7.0",
 "1.7.1",
 "1.7.3",
 "1.9.0",
 "1.9.3",
 "1.10.0",
 "1.10.2",
 "1.11.0",
 "2.0.0",
 "2.0.1",
 "2.1.0",
 "2.1.1",
 "2.1.2",
]

def main():

    euid = os.geteuid()
    if euid != 0:
        print("Script not started as root. Running sudo..")
        args = ['sudo', sys.executable] + sys.argv + [os.environ]
        os.execlpe('sudo', *args)

    for version in OVS_VERSIONS:
        print("---> Building Container for Open vSwitch %s" % version)

        subprocess.call("packer build -var 'ovs_version=%s' "
                        "packer/docker-ovs.json" % version,
                        shell=True
        )

    subprocess.call("docker push davetucker/docker-ovs")

if __name__ == "__main__":
    main()
